apiVersion: v1
kind: Secret
metadata:
  name: food-app-secret
type: Opaque
stringData:
  MONGO_URL: "mongodb+srv://Anthony:Onyejesi%401@anthony.pghyk.mongodb.net/Food_Ordering_System_ChopLife"
  MAPQUEST_API_KEY: "OJAsHPVY29yhwu8elVp7iB7yBrsA2AIM"